Dogebox-WG/dogeboxd

cmd/dogeboxd/main.go, cmd/dogeboxd/server.go, pkg/config.go, pkg/dogeboxd.go, pkg/rest.go, pkg/system/recovery.go, pkg/system/state.go, pkg/websocket.go
This adds recovery mode to dogeboxd. This currently limits functionality served by dogeboxd, and will serve a different entrypoint into dpanel once we add that.
Recovery mode is activated by either passing in a `--force-recovery` flag to the `dogeboxd` binary, or by having a file named `RECOVERY` or `RECOVERY.TXT` on a mounted `/dev/sd*` device.
Normal: 
```
adam@doge:/dogeboxd$ ./build/dogeboxd -v
==== hydrated local.Core
2024/08/19 16:51:44 No existing state file found. Starting with empty state.
Loading pup status: internal.dogeboxd
2024/08/19 16:51:44 Loaded 10 API routes
🔧 Starting 'Dogeboxd':
.. ok
🔧 Starting 'REST API':
.. ok
🔧 Starting 'System Updater':
.. ok
🔧 Starting 'System Monitor':
.. ok
🔧 Starting 'WSock Relay':
.. ok
```
Recovery:
```
adam@doge:/dogeboxd$ ./build/dogeboxd …
```
=> Add recovery mode

cmd/dogeboxd/main.go, cmd/dogeboxd/server.go, pkg/config.go, pkg/ui.go
As a temporary measure, we will serve dpanel through dogeboxd directly (rather than putting it in its own pup).
This currently assumes (by default) you have `dpanel` cloned into the parent directory of `dogeboxd`.
This will serve `index.html` in normal mode, and `index_recovery.html` in dogebox recovery mode.
=> Serve frontend UI

pkg/pup_manager.go, pkg/system/nix/nix.go, pkg/system/nix/templates/pup_container.nix, pkg/system/nix/templates/system.nix
- This changes the internal container network to `10.69.0.0/16` to avoid conflicting with home-networks that might be using `10.0.0.0/8` already.
- Fixes our nix files missing a couple of attributes needed for our shibe user. This isn't an issue in our release builds as we provide these in the pre-baked "system" configuration, but developers running dogeboxd in their own environments will likely not have these changes.
=> Change network to 10.69.0.0/16 + small nixfile fix

cmd/dogeboxd/server.go, pkg/pup/manifest.go, pkg/sys.go, pkg/system/nix/nix.go, pkg/system/nix/templates/firewall.nix, pkg/system/nix/templates/pup_container.nix, pkg/web/setup.go
This lets client pups listen on host ports, allowing the user to port-forward on their router and expose things to the internet.
This is required for running proper P2P nodes etc.
This adds a `ListenOnHost` to the manifest, under the exposes section. We have discussed changing this going forward, but this is the easiest go for now.
=> Allow pups to listen on host ports

pkg/pup/manifest.go, pkg/sys.go, pkg/system/nix/nix.go, pkg/system/nix/templates/system_container_config.nix
Adds a new manifest field `.container.requiresInternet` that whitelists the pup to allow traffic outbound to the internet.
This still blocks traffic inbound, and still blocks talking directly to other pups on `10.69.0.0/16`
=> Allow pups to request access to the internet

cmd/dogeboxd/server.go, pkg/dogeboxd.go, pkg/pup/manifest.go, pkg/sys.go, pkg/system/nix/nix.go, pkg/system/nix/templates/system_container_config.nix, pkg/web/store.go
This allows pups to talk to each other via TCP, instead of HTTP, for interfaces.
nb. This will break most existing pups (which are really just the few little test ones we have) because I have renamed (and added validation) for a couple of fields, namely in the exposes section.
=> Inter-pup TCP comms

Makefile, cmd/dogeboxd/main.go
This requires another nix security wrapper configured in `/etc/nixos/configuration.nix`
It must contain:
```nix
security.wrappers.dogeboxd = {
source = "/path/to/dogeboxd/build/dogeboxd";
capabilities = "cap_net_bind_service=+ep";
owner = "username";
group = "users";
};
```
Where `source` and `owner` have been updated to the correct values. `owner` should be your current non-root user.
This requires an equivalent change over in https://github.com/dogeorg/dogebox too.
=> Allow internal router to listen on :80 by default

cmd/dbx/cmd/enter-recovery-mode.go, cmd/dbx/cmd/is-recovery-mode.go, cmd/dogeboxd/main.go, pkg/sys.go, pkg/system/nix/nix.go, pkg/system/nix/templates/pup_container.nix, pkg/system/recovery.go
This prevents any pup containers from starting if we're booting into recovery mode.
TODO:
This requires another security wrapper in your `/etc/nixos/configuration.nix`, hopefully the last one.
```
security.wrappers.dbx = {
source = "/Users/adam/code/doge/dogeboxd/build/dbx";
owner = "adam";
group = "users";
};
```
Where `source` & `owner` are updated.
=> Prevent containers from starting in recovery mode

pkg/config.go, pkg/dogeboxd.go, pkg/pup_manager.go, pkg/sys.go, pkg/system/nix/nix.go, pkg/system/nix/templates/pup_container.nix
This will inject a bunch of environment variables that can be read by pups. 
This is mainly needed for pups that want to talk TCP to each other. With HTTP you would just hit the dbx router at `/pup/${interfaceName}` but that's not possible with TCP connections.
With this, we inject an environment variable named `DBX_IFACE_${IFACE_NAME}_HOST` and `DBX_IFACE_${IFACE_NAME}_PORT` that the process can read and use to understand where to connect to.
A list of things injected:
```bash
DBX_HOST=10.69.0.1               # Address of dogeboxd
DBX_PORT=80                      # Port for dogeboxd pup router
DBX_PUP_IP=10.69.0.4             # The IP address assigned to this pup
DBX_PUP_ID=1234snip              # The ID of this pup
DBX_IFACE_$_NAME=count-server          # The name of the pup assigned as …
```
=> Inject relevant container environment variables

pkg/pup/manifest.go
This will allow us to display upstream version metadata on pups, different to the version of the actual pup.
=> Add meta.upstreamVersions to manifest

cmd/dogeboxd/main.go, pkg/dogeboxd.go, pkg/sys.go, pkg/system/network/linux.go, pkg/system/network/persistor/nix.go, pkg/system/nix/nix-patch.go, pkg/system/nix/nix.go, pkg/system/updater.go, pkg/web/network.go, pkg/web/setup.go
This adds the concept of `nix patches`, which are an atomic-ly applied changeset to dogeboxd nix configuration files.
We snapshot your specified `nixDir` before making any changes, and if a rebuild fails, we trigger a rollback and replace everything with the known-working configuration.
```go
patch := nix.NewPatch()
patch.DoUpdate1() // Queued, but not executed
patch.DoUpdate2() // Queued, but not executed
// Queued operations are applied one by one, in order.
// And then a nixos-rebuild is triggered.
err := patch.Apply()
if err != nil {
// Failed, already rolled back, ready to clean up any other business logic you need to outside of nix
}
```
=> Nix Snapshots

cmd/dogeboxd/server.go, pkg/dogeboxd.go, pkg/events.go, pkg/sys.go, pkg/system/nix/nix.go, pkg/system/nix/templates/system.nix, pkg/system/ssh.go, pkg/system/updater.go, pkg/web/rest.go, pkg/web/setup.go, pkg/web/ssh.go
This provides management for SSH server & key management for physical hardware that don't have TTY-accessible consoles for getting shell access.
Also we persist the hostname chosen by the user now instead of hardcoding it to `dogebox`.
=> SSH Key management

pkg/pup/manifest.go, pkg/system/nix/templates/pup_container.nix
This is necessary so that pups can use pre-packaged, managed, nix `services.<blah>` configuration inside their containers, instead of having to manually rebuild things that community has already done.
A pup can now explicitly export a `services` directive block that gets merged into the containers services block.
eg:
Running mysql & caddy:
_pup.nix_
```nix
{ pkgs }:
let
files = pkgs.stdenv.mkDerivation {
name = "files";
src = ./.;
installPhase = ''
mkdir -p $out/opt/www
cp -r . $out/opt/www
'';
};
services = {
mysql = {
enable = true;
package = pkgs.mysql;
};
caddy = {
enable = true;
package = pkgs.caddy;
extraConfig = ''
:8090 {
root * ${files}/opt/www
handle_errors {
respond "404"
}
}
'';
};
};
in
{
inherit services;
}
```
=> Allow pups to define nix services to start

pkg/sys.go, pkg/system/nix/templates/system.nix, pkg/web/setup.go
Workaround for people so they can access their physical hardware without a proper management UI built. dpanel changes incoming.
=> Allow the user to specify an initial SSH key at setup

pkg/pup_manager.go, pkg/pups.go, pkg/system/nix/nix-patch.go, pkg/system/updater.go
This sets pups to `broken` and stores an error code on the state that can be used to convey information the client.
=> Properly handle half-installed & broken pups

cmd/dogeboxd/server.go, pkg/system/reflector.go, pkg/web/setup.go
This is probably the behaviour of what we actually want, as there is a small potential for the machine to be given a different IP address when it comes back online after being rebooted.
=> Submit info to reflector at boot instead of before reboot

pkg/system/nix/templates/dogebox.nix
This should prevent an issue where somebody wipes their `$data/nix/pup_` files and then tries to rebuild..
=> Only import pup files if they exist

cmd/_dbxroot/cmd/install-to-disk.go, cmd/dbx/cmd/get-disks.go, cmd/dbx/cmd/get-install-disks.go, pkg/sys.go, pkg/system/installation.go, pkg/utils/utils.go, pkg/web/install.go, pkg/web/rest.go, pkg/web/session.go, pkg/web/setup.go
This adds web APIs for system installation.
`GET /system/bootstrap` is modified to return a new `setupFact` named `installationMode`.
```json
{
"assets": {},
"states": {},
"stats": {},
"setupFacts": {
"installationMode": "canInstall",
...
}
}
```
There are 4 modes that can be returned:
- `isInstalled`: This means that the box has already been installed.
- `cannotInstall`: This occurs when the box has already been **set up**.
- `mustInstall`: The user is booting off read-only media and MUST install to continue use.
- `canInstall`: The user is booting off read-write media, and installation is optional to another disk.
A new `GET /system/install/disks` is added that returns a list of possible disk-installation targets:
```js
➜  http 127.0.0.1:3000/system/install/disks
[
{
"Name": "/dev/vdb", …
```
=> Add APIs for System Installation

cmd/dbx/cmd/get-install-disks.go, pkg/sys.go, pkg/system/installation.go, pkg/web/setup.go
This now returns:
```
{
..
name: "/dev/sda",
suitability: {
install: {
usable: true,
sizeOK: true
},
storage: {
usable: true,
sizeOK: false
}
}
}
```
For disks, so the frontend knows if it should display a disk size warning or not.
=> Expand disk usability information

Makefile, cmd/dbx/cmd/version.go, go.mod, go.sum, pkg/version/version.go, pkg/web/setup.go
This allows injecting release information into builds, allowing us to return the current "release" string to the client, as a precursor for system upgrades.
```sh
dogeboxd-env:/Users/adam/code/doge/dogeboxd $ DBX_NUR_HASH=my-fake-hash DBX_RELEASE=v0.3.0-beta make
...
dogeboxd-env:/Users/adam/code/doge/dogeboxd $ ./build/dbx version
Release: v0.3.0-beta
NurHash: my-fake-hash
Git: 0b89eb43c7ee41c6bd3a2ab44d556f482bd54e8f
Dirty: false
```
https://github.com/dogeorg/dogebox/blob/main/flake.nix#L34
https://github.com/dogeorg/dogebox-nur-packages/blob/main/pkgs/dogeboxd/default.nix#L46
=> Add release information to builds

pkg/sys.go, pkg/system/installation.go
This changes the installer to allow installing onto disks that are "used", and exposes a flag that lets the frontend show a warning if that's the case.
=> Expose disk usage to frontend, allow installing on used disks

pkg/system/updater.go
This makes it so that pups that require this key don't need to derive it themselves.
=> Also write extended delegated key to pup storage

cmd/_dbxroot/cmd/iwlist.go, pkg/system/network/wifi/iwlist.go
Use _dbxroot to interface with `iwlist` since it needs root permissions to do a scan
=> Listing Wifi networks

pkg/web/session.go
This is needed for the last installation step that provides a shutdown button
https://github.com/dogeorg/dpanel/issues/101
=> Add shutdown and recovery routes to whitelist

pkg/system/keymaps.go, pkg/system/keymaps.json
Trying to make listing the console keymaps better. Currently there's a mismatch between the listed keymaps from xkbcli and the list nixos loadkeys uses.
I'm certain that the command to invoke the `localectl list-keymaps` command could be better. But it's currently like this, since the command needs a temporary env var `SYSTEMD_KEYMAP_DIRECTORIES` set to the value of the evaluation of a nix statement with the appended directory to allow the command to list the proper keymaps.
`localectl` is really simple and only really lists the names of keymaps and doesn't provide any other information, so we'll lose out on getting any descriptions out.
=> Sort out keymap listing

pkg/system/installation.go
This fixes getting error installing to internal eMMC on the dogebox.
=> use all lowercase for nanopc-t6 to match os flake

flake.lock, pkg/dkm.go, pkg/web/rest.go, pkg/web/session.go
Change summary:
- Added new ChangePassword function. Takes a new password, and either the current password or seedphrase to pass to DKM
Sibling PR for dpanel - https://github.com/Dogebox-WG/dpanel/pull/125
Sibling PR for dkm - https://github.com/Dogebox-WG/dkm/pull/2
=> Allow change password via recovery mode with current password or seedphrase

pkg/pup/actions.go, pkg/pup/manager.go, pkg/pups.go, pkg/system/updater.go, pkg/web/admin_router.go
Recover pups that become stuck 'installing' - mark them as broken.
Update proxies not just when dogeboxd.PUP_ADOPTED fired but also for dogeboxd.PUP_CHANGED_INSTALLATION and dogeboxd.PUP_PURGED.
Check port for new pup is available.
Log expected hash when nix file hash doesn't match.
=> General improvements to pup install/uninstall workflows

pkg/dogeboxd.go, pkg/events.go, pkg/sys.go, pkg/system/nix/templates/system.nix, pkg/system/ssh.go, pkg/system/updater.go, pkg/utils/utils.go, pkg/web/binary_caches.go, pkg/web/rest.go, pkg/web/setup.go
This adds support for configuring Nix Binary Caches.
During setup, we'll allow users to opt-out (as most people will probably want?) of using the Foundation binary cache (https://nix.dogecoin.org) so that they don't have to compile pups such as Dogecoin Core, which typically take 20m+ on normal hardware. 
This doesn't mean that the end users have to trust published binaries though, as Nix still does its fully deterministic verification of the built binaries to ensure nothing has changed.
=> Binary Cache Support

cmd/_dbxroot/cmd/install-to-t6.go
Re-implement patch from @stephenquoll in https://github.com/Dogebox-WG/dogeboxd/commit/0fa21ed48d3eea424565f4b8e07257bd34c43463 to fix compile errors.
Correctly copies the partition with u-boot to the target disk. This fixes an issue that could come up with an interrupted install where the data became corrupted causing the boot process to fail due to the bootloader not getting installed correctly.
The RK3588 boot process is very particular about having things in just the right places.
=> Raw copy u-boot from boot media partition 1 to target disk partition 1

pkg/system/nix/templates/storage-overlay.nix
In some cases systemd was loading `mount-data-overlay` at the same time as `dogeboxd.service` causing the data-overlay for `/opt/dogebox` to not be properly mounted making `dogeboxd` see the original directory used during setup.
This only happened when using a separate storage device for data as selected during configuration and apparently only in a VM (tested on macOS with UTM)
=> make sure to run mount-data-overlay before dogeboxd
